package JFrames;

import db.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author EMMANUEL
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form SignupPage
     */
    public LoginPage() {
        initComponents();
    }

    //Validate textfields not empty
    public boolean validateLogin(){
//        String pwd = txt_pass.getText();
        String pwd = String.valueOf(txt_pass.getPassword());
                
        if (pwd.equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter Password");
            return false;
        }
        
        return true;
    }
    
    //verify credentials validity
    public void login(){
        int check = 0;
        String role = cbo_role.getSelectedItem().toString();
        String pwd = txt_pass.getText();
        
        try {
            Connection con = MyConnection.getConnection();
            
            PreparedStatement pst = con.prepareStatement("select * from users where role = ? and password = ?");
            
            //uses the value from the textfield to the colums in the db
            pst.setString(1, role);
            pst.setString(2, pwd);
            
            //returns ResultSet value
            ResultSet rs = pst.executeQuery();
            
            if (rs.next())
            {
            role = rs.getString("role");
            pwd = rs.getString("password");
//            String status = rs.getString(7);
            
 
            if(role.equals("Admin") && pwd.equals(pwd))
            {
                check = 1;
                if (rs.getString("status").equals("Approved"))
                {
//                  
                    new adminHome().setVisible(true);
                    dispose();
                }
                else
                    JOptionPane.showMessageDialog(null, "Please visit your System Admin for Assistance");

            }
            // To login as an Admin using a default password
//            if (role.equals("Admin") && pwd.equals("qwerty254"))
//                    || (role.equals(" Admin") && pwd.equals(pwd) && status.equals("Approved")))
//            {
//                check = 1;
//                setVisible(false);
//                new adminHome().setVisible(true);
//            } 
                        
            else if(role.equals("Dean") && pwd.equals(pwd))
            {
                check = 1;
                if (rs.getString("status").equals("Approved"))
                {
                    
                    new COD_Home().setVisible(true);
                    dispose();
                }
                else
                    JOptionPane.showMessageDialog(null, "Please visit your System Admin for Assistance");

            }
            
            else if(role.equals("COD") && pwd.equals(pwd))
            {
            
//                 Checks if the user is approved by the admin
                    check = 1;
                    if (rs.getString("status").equals("Approved"))
                    {
                        
                        new COD_Home().setVisible(true);
                        dispose();
                    }
                    else
                        JOptionPane.showMessageDialog(null, "Wait For Admin Approval");
             
            }
            else if(role.equals("Student") && pwd.equals(pwd))
            {
            
                check = 1;
                new studentHome().setVisible(true);
                dispose();
            }
 
            else   
                {
                    JOptionPane.showMessageDialog(this, "Sorry! Incorrect Credentials.");
//                    cbo_role.setSelectedIndex(-1);
                    txt_pass.setText("");
                    txt_pass.requestFocus();
                    
                }
        }
            
        }catch (Exception e){
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbl_close = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_login = new rojerusan.RSMaterialButtonCircle();
        btn_signup = new rojerusan.RSMaterialButtonCircle();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbo_role = new rojerusan.RSComboMetro();
        btn_forgotPass = new rojerusan.RSMaterialButtonCircle();
        lblinvisible = new javax.swing.JLabel();
        lblvisible = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 766));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Systems");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Display", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Students' Redressal App ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 300, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("EMMANUEL ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/library-3.png.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 810, 610));

        jLabel6.setFont(new java.awt.Font("Sitka Display", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Welcome To");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 180, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 770));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 60, 50));

        lbl_close.setFont(new java.awt.Font("Calibri Light", 1, 35)); // NOI18N
        lbl_close.setForeground(new java.awt.Color(255, 255, 255));
        lbl_close.setText("X");
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 6, 40, 30));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Welcome Back");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 160, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/icons8_Secure_50px.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 60, 50));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Password");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 180, -1));

        btn_login.setBackground(new java.awt.Color(102, 102, 255));
        btn_login.setText("Login");
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginMouseClicked(evt);
            }
        });
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel2.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 380, 80));

        btn_signup.setBackground(new java.awt.Color(255, 51, 51));
        btn_signup.setText("Signup");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        jPanel2.add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 380, 80));

        jLabel16.setFont(new java.awt.Font("Stencil", 0, 25)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Login Page");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 230, -1));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Role");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 180, -1));

        cbo_role.setBackground(new java.awt.Color(102, 153, 255));
        cbo_role.setForeground(new java.awt.Color(0, 0, 0));
        cbo_role.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Student", "COD", "Dean", "Admin" }));
        cbo_role.setColorBorde(new java.awt.Color(109, 109, 109));
        cbo_role.setColorFondo(new java.awt.Color(102, 153, 255));
        cbo_role.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jPanel2.add(cbo_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 260, 40));

        btn_forgotPass.setBackground(new java.awt.Color(102, 153, 0));
        btn_forgotPass.setText("FORGOT PASSWORD?");
        btn_forgotPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_forgotPassActionPerformed(evt);
            }
        });
        jPanel2.add(btn_forgotPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 380, 80));

        lblinvisible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/invisible.png"))); // NOI18N
        lblinvisible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblinvisibleMouseClicked(evt);
            }
        });
        jPanel2.add(lblinvisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 40, 40));

        lblvisible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/visible.png"))); // NOI18N
        lblvisible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblvisibleMouseClicked(evt);
            }
        });
        jPanel2.add(lblvisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 40, 40));

        txt_pass.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jPanel2.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 270, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 510, 760));

        setSize(new java.awt.Dimension(1366, 766));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        SignupPage page = new SignupPage();
        page.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_signupActionPerformed

    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
        int a= JOptionPane.showConfirmDialog(null, "Do you really want to Close Application?", "Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
        
    }//GEN-LAST:event_lbl_closeMouseClicked

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        if (validateLogin()){
            login();
        }
                        
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
        if (validateLogin()){
            login();
        }
        
    }//GEN-LAST:event_btn_loginMouseClicked

    private void btn_forgotPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_forgotPassActionPerformed
        forgot_password page = new forgot_password();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_forgotPassActionPerformed

    private void lblinvisibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblinvisibleMouseClicked
        txt_pass.setEchoChar((char) 0);
        lblinvisible.setVisible(false);
        lblvisible.setVisible(true);
    }//GEN-LAST:event_lblinvisibleMouseClicked

    private void lblvisibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvisibleMouseClicked
        txt_pass.setEchoChar('*');
        lblinvisible.setVisible(true);
        lblvisible.setVisible(false);
    }//GEN-LAST:event_lblvisibleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle btn_forgotPass;
    private rojerusan.RSMaterialButtonCircle btn_login;
    private rojerusan.RSMaterialButtonCircle btn_signup;
    private rojerusan.RSComboMetro cbo_role;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lblinvisible;
    private javax.swing.JLabel lblvisible;
    private javax.swing.JPasswordField txt_pass;
    // End of variables declaration//GEN-END:variables
}
